### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by adriangb** [adriangb/anydep#3]
I'm thinking of publishing a super alpha version of this package (after a bit of cleanup and writing some minimal docs), mainly because I want to play around with adding DI to Textual or other things outside of FastAPI. Worst case is it makes this package better and gives some ideas for FastAPI.

But that requires coming up with a real name. Right now this is called "anydep" mainly because it does dependency injection and uses anyio to be IO agnostic, but given that that is a minor implementation detail, I'm not sure that should the the package name. Some options that are available on pypi are:
- anydep: current name, reasons above
- di (yes, just `di`): this is the shortest name possible, and DI is a common acronym
- autodi / autodep: in reference to the fact that this package "autowires" (the terminology used by many DI systems for discovering transitive dependencies via reflection)

Any thoughts @graingert ?

**Comment by graingert** [comment]
@adriangb wow `di` sounds great!

**Comment by graingert** [comment]
are you https://pypi.org/user/adriangb/ on pypi?

**Comment by adriangb** [comment]
yep

**Comment by graingert** [comment]
nice - di is now registered if you upload what you have here you can yank the `di==0.0.0` release

**Comment by adriangb** [comment]
thanks! i'm going to try to do a bit of cleanup and documentation first 😃
